# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Luke Hodgkinson (dot com)
email: him@lukehodgkinson.com
description: Probably just a placeholder, but there might be content.
baseurl: "" # the subpath of your site, e.g. /blog
url: "www.lukehodgkinson.com" # the base hostname & protocol for your site
twitter_username: beluho
github_username:  beluho

# Build settings
markdown: kramdown
